#ifndef SERVERCLIENT_COMMON_H
#define SERVERCLIENT_COMMON_H

#define ICMP_CONN_CLIENT_TYPE 80
#define ICMP_CONN_CLIENT_CODE 0

#define ICMP_CONN_SERVER_TYPE 81
#define ICMP_CONN_SERVER_CODE 0

#endif //SERVERCLIENT_COMMON_H
